service: cla-bot

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/clabot-log"
      
functions:
  cla-bot:
    handler: cla-bot/index.handler
    environment: ${file(./cla-bot/serverless.env.yml):${opt:stage}}
    events:
      - http:
          path: cla-check
          method: post
  cla-bot-logs:
    handler: cla-bot-logs/index.handler
    environment: ${file(./cla-bot-logs/serverless.env.yml):${opt:stage}}
    events:
      - http:
          path: get-logs
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                url: true
